
DROP TABLE IF EXISTS `spell_dbc`;

CREATE TABLE IF NOT EXISTS `spell_dbc` (
  `Id` int(10) NOT NULL,
  `Attributes` int(10) NOT NULL,
  `AttributesEx` int(10) NOT NULL,
  `AttributesEx2` int(10) NOT NULL,
  `AttributesEx3` int(10) NOT NULL,
  `AttributesEx4` int(10) NOT NULL,
  `AttributesEx5` int(10) NOT NULL,
  `AttributesEx6` int(10) NOT NULL,
  `AttributesEx7` int(10) NOT NULL,
  `AttributesEx8` int(10) NOT NULL,
  `AttributesEx9` int(10) NOT NULL,
  `AttributesEx10` int(10) NOT NULL,
  `CastingTimeIndex` int(10) NOT NULL,
  `DurationIndex` int(10) NOT NULL,
  `powerType` int(10) NOT NULL,
  `rangeIndex` int(10) NOT NULL,
  `SchoolMask` int(10) NOT NULL,
  `runeCostID` int(10) NOT NULL,
  `SpellDifficultyId` int(10) NOT NULL,
  `SpellCoef` float NOT NULL,
  `SpellScalingId` int(10) NOT NULL,
  `SpellAuraOptionsId` int(10) NOT NULL,
  `SpellAuraRestrictionsId` int(10) NOT NULL,
  `SpellCastingRequirementsId` int(10) NOT NULL,
  `SpellCategoriesId` int(10) NOT NULL,
  `SpellClassOptionsId` int(10) NOT NULL,
  `SpellCooldownsId` int(10) NOT NULL,
  `SpellEquippedItemsId` int(10) NOT NULL,
  `SpellInterruptsId` int(10) NOT NULL,
  `SpellLevelsId` int(10) NOT NULL,
  `SpellPowerId` int(10) NOT NULL,
  `SpellReagentsId` int(10) NOT NULL,
  `SpellShapeshiftId` int(10) NOT NULL,
  `SpellTargetRestrictionsId` int(10) NOT NULL,
  `SpellTotemsId` int(10) NOT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
